### ISSUE TITLE
Error while running multiprocessing tools

### ISSUE THREAD

**Issue by astro-fermi** [kialio/gtapps_mp#2]
Dear Sir,

I was trying to do fine time binned analysis of some blazars by using LATAnalysisScripts package. I am using weekly photon files (for e.g. lat_photon_weekly_w011_p130_v001.fits & similarly other files) for input. Unfortunately I am facing following error-

Input config file----
[common]
irfs = P7SOURCE_V6
multicore = 3
verbosity = 2
binned = False
base = J0324
eventclass = 2

[quickAnalysis]
rad = 10
tmin = 399524403
ra = 51.2096
emin = 100
emax = 100000
tmax = 399529803
dec = 34.143
convtype = -1
zmax = 100
binsize = 0.1

[quickLike]
sourcename = _2FGLJ0324.8+3408
model = J0324_model.xml
drmtol = 0.01
mintol = 1e-8

------------------------------------------Output---------------------------------------
------ gtselect & gtmktime finished --------
2013-09-17 00:10:15,188 - quickAnalysis - INFO - **_Running gtltcube**_
Opening event file to determine start and stop times...
Opening SC file to determine break points...
Spawning 3 jobs...
Starting calculation on interval 399524403.0 to 399525711.6
Starting calculation on interval 399525711.6 to 399526972.6
Starting calculation on interval 399526972.6 to 399529803.0
Completed calculation on interval 399525711.6 to 399526972.6
Working on file J0324_SC.fits
Completed calculation on interval 399526972.6 to 399529803.0
Working on file J0324_SC.fits
Completed calculation on interval 399524403.0 to 399525711.6
Combining temporary files...
Caught N3tip12TipExceptionE at the top level: File not in FITS or Root format: /tmp/tmp1IfW7A.fits
Deleting temporary files...

As you would see that I have used 3 cores for this operation. Now just to check, I changed the number of cores from 3 to 2 & results are as follows-

New Input config file---
[common]
irfs = P7SOURCE_V6
multicore = 2
verbosity = 2
binned = False
base = J0324
eventclass = 2

[quickAnalysis]
rad = 10
tmin = 399524403
ra = 51.2096
emin = 100
emax = 100000
tmax = 399529803
dec = 34.143
convtype = -1
zmax = 100
binsize = 0.1

[quickLike]
sourcename = _2FGLJ0324.8+3408
model = J0324_model.xml
drmtol = 0.01
mintol = 1e-8

-----------------------------Output---------------------------------------------------------------
--------gtselect & gtmktime finished -------
2013-09-17 00:16:22,528 - quickAnalysis - INFO - **_Running gtltcube**_
Opening event file to determine start and stop times...
Opening SC file to determine break points...
Spawning 2 jobs...
Starting calculation on interval 399524403.0 to 399526341.6
Starting calculation on interval 399526341.6 to 399529803.0
Working on file J0324_SC.fits
Completed calculation on interval 399526341.6 to 399529803.0
Working on file J0324_SC.fits
Completed calculation on interval 399524403.0 to 399526341.6
Combining temporary files...
Deleting temporary files...
## 2013-09-17 00:16:25,201 - quickAnalysis - INFO - **_Running gtcountsmap**_

Surprisingly, this time no error came. Further, I thought it may be because of taking very small time bin (~ 100 mins), so I tried to run weekly binned analysis covering ~5 year of Fermi operation. Out of 266 such operations, I faced this error 4 times.

I request you to kindly take a look into the problem. Please let me know if you need more information.

Thank you very much.

-- Vaidehi

**Comment by Gajuharale** [comment]
Dear all
 I am getting an error 
Caught N3tip12TipExceptionE at the top level: File not found: Abell1_2744_filtered.fits
Traceback (most recent call last):
  File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/bin/quickAnalysis", line 5, in <module>
    quickAnalysis.cli()
  File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickAnalysis.py", line 490, in cli
    qA.runAll(True)         
  File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickAnalysis.py", line 381, in runAll
    self.runGTI(run)
  File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickAnalysis.py", line 166, in runGTI
    qU.runCommand(maketime,self.logger,run)
  File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickUtils.py", line 250, in runCommand
    AppCommand.run(print_command=printCmd)
  File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python/GtApp.py", line 72, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtmktime execution failed
 While performing LAT quickanalysis

I request to all kindly look in to the problem. If further information need please know me

Thank you
