### ISSUE TITLE
LAT Analysis

### ISSUE THREAD

**Issue by Gajuharale** [kialio/gtapps_mp#8]
Dear all
I am getting an error
Caught N3tip12TipExceptionE at the top level: File not found: Abell1_2744_filtered.fits
Traceback (most recent call last):
File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/bin/quickAnalysis", line 5, in
quickAnalysis.cli()
File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickAnalysis.py", line 490, in cli
qA.runAll(True)
File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickAnalysis.py", line 381, in runAll
self.runGTI(run)
File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickAnalysis.py", line 166, in runGTI
qU.runCommand(maketime,self.logger,run)
File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickUtils.py", line 250, in runCommand
AppCommand.run(print_command=printCmd)
File "/home/gajanan/Downloads/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python/GtApp.py", line 72, in run
raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtmktime execution failed
While performing LAT quickanalysis

I request to all kindly look in to the problem. If further information need please know me

Thank you

**Comment by Gajuharale** [comment]
This error came when I run gtmktime.
